import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import mysql from "mysql2/promise";

test("APP, requisition and appropriation records enforce scope, atomic audits and concurrent state guards", { skip: process.env.RUN_PROCUREMENT_DB_TESTS !== "1", timeout: 180000 }, async (t) => {
  const scratch = `impbbms_requisition_test_${crypto.randomBytes(8).toString("hex")}`;
  const port = Number(process.env.PROCUREMENT_TEST_DB_PORT ?? 33317);
  Object.assign(process.env, { DB_HOST: "127.0.0.1", DB_PORT: String(port), DB_NAME: scratch, DB_USER: "root", DB_PASSWORD: "", NODE_ENV: "test" });
  const admin = await mysql.createConnection({ host: "127.0.0.1", port, user: "root", password: "" });
  assert.match(scratch, /^impbbms_requisition_test_[a-f0-9]{16}$/);
  await admin.query(`CREATE DATABASE \`${scratch}\``);
  let db;
  t.after(async () => { await db?.close(); assert.match(scratch, /^impbbms_requisition_test_[a-f0-9]{16}$/); await admin.query(`DROP DATABASE \`${scratch}\``); await admin.end(); });
  const m = await import("../models/index.js"); db = m.sequelize; await db.sync();
  const appApi = await import("../controllers/appEntryController.js");
  const prApi = await import("../controllers/prController.js");
  const budgetApi = await import("../controllers/appropriationController.js");
  const { verifyChain } = await import("../services/auditLog.js");
  const officeA = await m.Department.create({ name: "Health", code: "HEALTH" });
  const officeB = await m.Department.create({ name: "Engineering", code: "ENG" });
  const roles = {};
  const user = async (name, key, departmentId, permissions) => {
    const role = roles[key] ??= await m.Role.create({ key, name: key });
    const actor = await m.User.create({ name, email: `${name}@example.test`, password: "ExamplePassword123!", roleId: role.id, departmentId, status: "active" });
    actor.Role = role; actor.testPermissions = permissions; return actor;
  };
  const requester = await user("requester", "departmentRequester", officeA.id, ["app.view", "app.create", "app.submit", "app.revise", "pr.view", "pr.create"]);
  const other = await user("other", "departmentRequester", officeB.id, requester.testPermissions);
  const noDepartment = await user("unassigned", "departmentRequester", null, requester.testPermissions);
  const head = await user("head", "headOfOffice", officeA.id, ["pr.view", "pr.create", "pr.endorse"]);
  const central = await user("central", "bacSecretariat", officeA.id, ["app.view", "app.create", "app.submit", "app.consolidate", "app.revise", "pr.view", "pr.create", "pr.review"]);
  const accountant = await user("accountant", "municipalAccountant", officeB.id, ["pr.view", "pr.obligate"]);
  const budget = await user("budget", "budgetOfficer", officeB.id, ["pr.view", "pr.certify", "budget.certify", "budget.manageAppropriations"]);
  const chair = await user("chair", "bacChairperson", null, ["pr.view", "pr.determineMode"]);
  const vice = await user("vice", "bacViceChairperson", null, ["pr.view", "pr.determineMode"]);
  const members = [];
  for (let i = 0; i < 3; i++) members.push(await user(`member${i}`, "bacMember", null, ["pr.view"]));
  const attendance = { attendingMemberIds: [chair.id, vice.id, members[0].id], presidingMemberId: chair.id };
  const program = await m.InvestmentProgram.create({ fiscalYear: 2028, title: "Approved program", status: "adopted" });
  const mode = await m.ProcurementMode.create({ key: "competitiveBidding", name: "Competitive Bidding", minimumOffers: 2 });
  let serial = 0;
  const funding = (departmentId, amount = 100000, fiscalYear = 2028) => m.Appropriation.create({ fiscalYear, ordinanceNo: `ORD-${++serial}`, title: "Office appropriation", amount, departmentId, status: "enacted", expenseClass: "mooe", fund: "generalFund" });
  const aip = (departmentId) => m.AipEntry.create({ title: "Office investment", estimatedCost: 100000, investmentProgramId: program.id, implementingUnitId: departmentId });
  const fundingA = await funding(officeA.id), fundingB = await funding(officeB.id);
  const aipA = await aip(officeA.id), aipB = await aip(officeB.id);
  const appPayload = (department = officeA, fund = fundingA, investment = aipA, abc = 1000) => ({ projectTitle: `Procurement plan ${++serial}`, abc, fiscalYear: 2028, implementingUnitId: department.id, appropriationId: fund.id, aipEntryId: investment.id, targetStartQuarter: "Q1", targetCompletionQuarter: "Q4", procurementMode: mode.key, planCycle: "final", category: "goods" });
  const makeApp = async (department = officeA, fund = fundingA, abc = 1000) => m.AppEntry.create({ ...appPayload(department, fund, department.id === officeA.id ? aipA : aipB, abc), status: "locked", createdById: department.id === officeA.id ? requester.id : other.id });
  const items = (amount) => [{ description: "Required office supplies", quantity: 1, unit: "lot", unitCost: amount }];
  const call = async (handler, actor, params = {}, body = {}, query = {}) => {
    let output; let statusCode = 200;
    const req = { currentUser: actor, params, body, query, permissions: new Set(actor.testPermissions), ip: "127.0.0.1" };
    await handler(req, { status(code) { statusCode = code; return this; }, json(value) { output = value; return this; } });
    if (statusCode >= 400) throw Object.assign(new Error(output?.message ?? "Request rejected"), { status: statusCode });
    return output;
  };
  const createPr = (actor, app, amount) => call(prApi.createPr, actor, {}, { appEntryId: app.id, purpose: "Office operations", dateRequired: "2028-12-31", lineItems: items(amount) });
  const makePr = async (app, amount, status) => {
    const pr = await m.PrHeader.create({ prNumber: `PR-RECORD-${++serial}`, dateRequired: "2028-12-31", purpose: "Office operations", appEntryId: app.id, departmentId: app.implementingUnitId, requesterId: requester.id, totalAmount: amount, status });
    await m.PrLineItem.create({ ...items(amount)[0], lineTotal: amount, prHeaderId: pr.id }); return pr;
  };

  await t.test("requesters cannot create or move plans across departments; central officers retain authorized creation", async () => {
    await assert.rejects(call(appApi.createAppEntry, requester, {}, appPayload(officeB, fundingB, aipB)), /own department/);
    await assert.rejects(call(appApi.createAppEntry, requester, {}, appPayload(officeA, fundingB, aipA)), /appropriation.*another department/i);
    const created = await call(appApi.createAppEntry, requester, {}, appPayload());
    await assert.rejects(call(appApi.updateAppEntry, requester, { id: created.id }, { implementingUnitId: officeB.id }), /own department/);
    await assert.rejects(call(appApi.transitionAppEntry, other, { id: created.id }, { action: "submit" }), /own department/);
    const changed = await call(appApi.updateAppEntry, requester, { id: created.id }, { description: "Revised office requirements", abc: 900, status: "locked" });
    assert.equal(changed.status, "draft"); assert.equal(changed.abc, 900);
    const centralPlan = await call(appApi.createAppEntry, central, {}, appPayload(officeB, fundingB, aipB));
    assert.equal(centralPlan.implementingUnitId, officeB.id);
    assert.deepEqual(await call(appApi.listAppEntries, noDepartment, {}, {}, { fiscalYear: 2028 }), []);
    const audit = await m.AuditLog.findOne({ where: { actionType: "app.updated", entityId: created.id } });
    assert.equal(audit.beforeState.abc, "1000.00"); assert.equal(Number(audit.afterState.abc), 900);
    assert.equal(audit.beforeState.projectTitle, changed.projectTitle); assert.equal(audit.afterState.description, "Revised office requirements");
    assert.equal(audit.actorId, requester.id); assert.equal(audit.actorRole, "departmentRequester");
  });
  await t.test("APP funding reservations and duplicate submit actions are serialized", async () => {
    const limited = await funding(officeA.id, 100);
    const results = await Promise.allSettled([1, 2].map(() => call(appApi.createAppEntry, requester, {}, appPayload(officeA, limited, aipA, 70))));
    assert.equal(results.filter((result) => result.status === "fulfilled").length, 1);
    const entry = results.find((result) => result.status === "fulfilled").value;
    const transitions = await Promise.allSettled([1, 2].map(() => call(appApi.transitionAppEntry, requester, { id: entry.id }, { action: "submit" })));
    assert.equal(transitions.filter((result) => result.status === "fulfilled").length, 1);
    assert.equal(await m.AuditLog.count({ where: { actionType: "app.transition", entityId: entry.id } }), 1);
  });
  await t.test("requisitions derive ownership from the approved plan and scoped heads see only their queue", async () => {
    const appA = await makeApp(), appB = await makeApp(officeB, fundingB);
    await assert.rejects(createPr(requester, appB, 50), /own department/);
    const a = await createPr(requester, appA, 50), b = await createPr(central, appB, 60);
    assert.equal((await m.PrHeader.findByPk(b.id)).departmentId, officeB.id);
    await assert.rejects(call(prApi.updatePr, requester, { id: b.id }, { purpose: "Foreign edit" }), /own department/);
    await call(prApi.updatePr, central, { id: b.id }, { purpose: "Authorized central correction" });
    await assert.rejects(call(prApi.transitionPr, other, { id: a.id }, { action: "submit" }), /own department/);
    await call(prApi.transitionPr, requester, { id: a.id }, { action: "submit" });
    await call(prApi.transitionPr, central, { id: b.id }, { action: "submit" });
    await assert.rejects(call(prApi.transitionPr, head, { id: b.id }, { action: "endorse" }), /this department/i);
    await call(prApi.transitionPr, head, { id: a.id }, { action: "endorse" });
    const visible = await call(prApi.listPrs, head, {}, {}, { fiscalYear: 2028 });
    assert.ok(visible.some((row) => row.id === a.id)); assert.ok(!visible.some((row) => row.id === b.id));
    assert.deepEqual(await call(prApi.listPrs, noDepartment, {}, {}, { fiscalYear: 2028 }), []);
    assert.ok((await call(prApi.listPrs, accountant, {}, {}, { fiscalYear: 2028 })).some((row) => row.id === b.id));
    const assigned = await user("assignedHead", "departmentRequester", officeB.id, ["pr.create"]);
    const pending = await makePr(appA, 30, "pendingDepartmentHeadEndorsement");
    await officeA.update({ headUserId: assigned.id });
    await call(prApi.transitionPr, assigned, { id: pending.id }, { action: "endorse" });
  });
  await t.test("concurrent PR submissions cannot exceed the same APP balance", async () => {
    const app = await makeApp(officeA, fundingA, 100);
    const a = await createPr(requester, app, 70), b = await createPr(requester, app, 70);
    const results = await Promise.allSettled([a, b].map((pr) => call(prApi.transitionPr, requester, { id: pr.id }, { action: "submit" })));
    assert.equal(results.filter((result) => result.status === "fulfilled").length, 1);
    assert.equal((await prApi.remainingBalanceFor(app.id)).remaining, 30);
  });
  await t.test("duplicate obligations and competing commitments cannot overspend; returns retain ORS history", async () => {
    const fund = await funding(officeA.id, 1000);
    const appA = await makeApp(officeA, fund, 800), appB = await makeApp(officeA, fund, 800);
    for (const app of [appA, appB]) await m.ProjectAllocation.create({ appEntryId: app.id, appropriationId: fund.id, fiscalYear: app.fiscalYear, amount: 800, status: "active" });
    const a = await makePr(appA, 800, "pendingAccountantObligation"), b = await makePr(appB, 800, "pendingAccountantObligation");
    const results = await Promise.allSettled([a, b].map((pr) => call(prApi.transitionPr, accountant, { id: pr.id }, { action: "obligate" })));
    assert.equal(results.filter((result) => result.status === "fulfilled").length, 1);
    const winner = results.find((result) => result.status === "fulfilled").value;
    await assert.rejects(call(prApi.transitionPr, accountant, { id: winner.id }, { action: "obligate" }), /Cannot.*obligate/i);
    const obligation = await m.Obligation.findOne({ where: { prHeaderId: winner.id } });
    assert.equal(Number(obligation.amount), 800); assert.match(obligation.obligationNo, /2028/);
    await call(prApi.transitionPr, chair, { id: winner.id }, { action: "return", remarks: "Correct the procurement requirements before determining the mode." });
    assert.equal((await obligation.reload()).status, "cancelled");
    const returned = await m.PrHeader.findByPk(winner.id); assert.equal(returned.fundsReservedAt, null); assert.equal(returned.obligatedById, null);
    const audit = await m.AuditLog.findOne({ where: { actionType: "pr.transition", entityId: winner.id }, order: [["id", "DESC"]] });
    assert.equal(audit.beforeState.obligations[0].status, "obligated"); assert.equal(audit.afterState.obligations[0].status, "cancelled");
    assert.equal(audit.beforeState.lineItems.length, 1);
  });
  await t.test("duplicate approvals and BAC mode determinations cannot repeat official actions", async () => {
    const app = await makeApp();
    const mayor = await user("mayor", "hope", null, ["pr.approve"]);
    const approving = await makePr(app, 10, "pendingMayorApproval");
    const approvals = await Promise.allSettled([1, 2].map(() => call(prApi.transitionPr, mayor, { id: approving.id }, { action: "approve" })));
    assert.equal(approvals.filter((result) => result.status === "fulfilled").length, 1);
    const determining = await makePr(app, 20, "pendingModeDetermination");
    const decisions = await Promise.allSettled([1, 2].map(() => call(prApi.transitionPr, chair, { id: determining.id }, { action: "determineMode", procurementModeKey: mode.key, justification: "Approved competitive procurement plan.", ...attendance })));
    assert.equal(decisions.filter((result) => result.status === "fulfilled").length, 1);
    assert.equal(await m.AuditLog.count({ where: { actionType: "bac.modeDetermined", entityId: determining.id } }), 1);
  });
  await t.test("audit failures roll back plan creation, requisition edits and appropriation changes", async () => {
    const app = await makeApp(); const pr = await createPr(requester, app, 40);
    const beforeAppCount = await m.AppEntry.count(); const before = (await m.PrHeader.findByPk(pr.id)).get({ plain: true });
    const beforeItems = (await m.PrLineItem.findAll({ where: { prHeaderId: pr.id } })).map((row) => row.get({ plain: true }));
    const editableFunding = await funding(officeA.id, 100, 2032);
    await editableFunding.update({ status: "draft" });
    const beforeFunding = (await editableFunding.reload()).get({ plain: true });
    m.AuditLog.addHook("beforeCreate", "recordsAuditFailure", () => { throw new Error("audit storage unavailable"); });
    await assert.rejects(call(appApi.createAppEntry, requester, {}, appPayload()), /audit storage unavailable/);
    await assert.rejects(call(prApi.updatePr, requester, { id: pr.id }, { purpose: "Must roll back", lineItems: items(45) }), /audit storage unavailable/);
    await assert.rejects(call(budgetApi.updateAppropriation, budget, { id: editableFunding.id }, { remarks: "Must roll back" }), /audit storage unavailable/);
    m.AuditLog.removeHook("beforeCreate", "recordsAuditFailure");
    assert.equal(await m.AppEntry.count(), beforeAppCount);
    assert.deepEqual((await m.PrHeader.findByPk(pr.id)).get({ plain: true }), before);
    assert.deepEqual((await m.PrLineItem.findAll({ where: { prHeaderId: pr.id } })).map((row) => row.get({ plain: true })), beforeItems);
    assert.deepEqual((await editableFunding.reload()).get({ plain: true }), beforeFunding);
  });
  await t.test("appropriation authority and reenactment retain complete before/after evidence", async () => {
    await assert.rejects(call(budgetApi.updateAppropriation, budget, { id: fundingA.id }, { amount: 1 }), /independently approved/);
    await assert.rejects(call(budgetApi.updateAppropriation, budget, { id: fundingA.id }, { departmentId: officeB.id }), /independently approved/);
    await funding(officeA.id, 100, 2030);
    const editable = await funding(officeA.id, 100, 2032);
    await editable.update({ status: "draft" });
    await call(budgetApi.updateAppropriation, budget, { id: editable.id }, { title: "Corrected ordinance purpose", remarks: "Documented correction" });
    const audit = await m.AuditLog.findOne({ where: { actionType: "appropriation.amended", entityId: editable.id } });
    assert.equal(audit.beforeState.title, "Office appropriation"); assert.equal(audit.afterState.title, "Corrected ordinance purpose");
    const races = await Promise.allSettled([1, 2].map(() => call(budgetApi.reenactPriorYear, budget, {}, { fiscalYear: 2031 })));
    assert.equal(races.filter((result) => result.status === "fulfilled").length, 0);
    assert.match(races[0].reason.message, /documented budget control request/);
    assert.equal(await m.Appropriation.count({ where: { fiscalYear: 2031, type: "reenacted" } }), 0);
    assert.equal((await verifyChain({})).intact, true);
  });
});
